### PR TITLE
first schema iteration finished, png of schema design in project. upd…

### PR DESCRIPTION
**Pull request by lilvina**
…ates specs to refelect work done

### CODE REVIEW

**Review by DianaVashti — COMMENTED** [review]
Questions I have: 
Why do you have price and quantity on ingredients table. Quantity makes me think inventory, which would make me think price means cost to the store? (unless the plan was to allow customers to order double of a topping?  If that's the case I am fine with that table)

Otherwise, this looks good to me!

👍

**Comment by Moniarchy** [comment]
In this ingredients table, quantity represents how many the store has in stock. Price represents the cost to the customer. (olives might be worth .50) Could this be further clarified? Would you recommend having a separate inventory table?

**Comment by Moniarchy** [comment]
@AbrahamFergie does this explanation make sense to you? What other feedback might you have for us?

**Review by AbrahamFergie — APPROVED** [review]
My feedback is to consolidate your schema into bigger tables that have more columns. since this app is still relatively small I wouldn't see a point in separating the data out to that extent.

**Comment by Moniarchy** [comment]
@AbrahamFergie @DianaVashti maybe we could talk about our schema design? i'm feeling pretty confident about it--I come from the jrob school of thought which is many smaller "modules."

**Pull request merged**
